### ISSUE TITLE
create tests for every feature/function

### ISSUE THREAD

**Issue by zevaverbach** [cssidy/emailbot#1]
I suggest using test.py and putting them all in a `tests` directory.
1. write a test for every existing function.
2. write a test for every feature/function that you'd like to have (before writing the code for it).
3. run the tests.
4. write/edit code so that one more test passes.
5. repeat 3 and 4 until all tests pass.
6. return to 2.

issue #2 is a prerequisite for this.

**Comment by zevav** [comment]
@cssidy have a crack at this, and let me know if you get stuck.  The first thing is to test EmailFetcher and its methods, then the Email model and its methods.
